version = 0.1
[default.deploy.parameters]
stack_name = "sam-app1"
resolve_s3 = true
s3_prefix = "sam-app1"
region = "us-east-1"
profile = "alihasnat2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
